language: python
python:
  - 3.5
services:
  - docker
before_install:
  - pip install -r requirements.txt
install:
    - flask run
script:
  - curl 127.0.0.1:5000
after_script:
  - docker build -t dreckguy/decryption-challenge .
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - docker push dreckguy/decryption-challenge
