language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - pip install -r requirements.txt
install:
  - python server.py &
after_install:
  - echo 'sleeping...'
  - sleep 5
  - echo 'finished sleeping'
script:
  - curl 127.0.0.1:5000/status | jq '.status' | grep -q 'completed'
  - curl 127.0.0.1:5000/message | jq '.message'
after_script:
  - docker build -t dreckguy/decryption-challenge .
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - docker push dreckguy/decryption-challenge