dist: xenial
language: python
services:
  - docker
before_install:
  - bash scripts/install_python.sh
  - python3.7 -V | grep 3.7.2 
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.7
install:
  - pip install -r requirements.txt
  - export FLASK_APP=server.py
before_script:
  - python3.7 -m flask run
script:
  - curl 127.0.0.1:5000
after_script:
  - docker build -t dreckguy/decryption-challenge .
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - docker push dreckguy/decryption-challenge