dist: xenial
language: python
services:
  - docker
before_install:
  - bash scripts/install_python.sh
install:
  - echo "installing...."
script:
  - python -V
after_script:
  - docker build -t dreckguy/decryption-challenge .
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
  - docker push dreckguy/decryption-challenge